defaults:
  - text2semantic_finetune
  - _self_

project: text2semantic_400m_finetune_lora
# Model Configuration
model:
  save_lora_only: true
  lora_config:
    _target_: fish_speech.models.text2semantic.lit_module.LoraConfig
    r: 8
    lora_alpha: 16
