site_name: OpenAudio
site_description: Targeting SOTA TTS solutions.
site_url: https://speech.fish.audio

# Repository
repo_name: fishaudio/fish-speech
repo_url: https://github.com/fishaudio/fish-speech
edit_uri: blob/main/docs

# Copyright
copyright: Copyright &copy; 2023-2025 by Fish Audio

theme:
  name: material
  favicon: assets/openaudio.png
  language: en
  features:
    - content.action.edit
    - content.action.view
    - navigation.tracking
    - navigation.footer
    # - navigation.tabs
    - search
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  logo: assets/openaudio.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      font:
        code: Roboto Mono

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      font:
        code: Roboto Mono

nav:
  - Introduction: en/index.md
  - Installation: en/install.md
  - Finetune: en/finetune.md
  - Inference: en/inference.md
  - Samples: en/samples.md

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
        - zh
        - ja
        - pt
        - ko
        - ar
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 简体中文
          build: true
          nav:
            - 介绍: zh/index.md
            - 安装: zh/install.md
            - 微调: zh/finetune.md
            - 推理: zh/inference.md
            - 示例: zh/samples.md
        - locale: ja
          name: 日本語
          build: true
          nav:
            - はじめに: ja/index.md
            - インストール: ja/install.md
            - ファインチューニング: ja/finetune.md
            - 推論: ja/inference.md
            - サンプル: ja/samples.md
        - locale: pt
          name: Português (Brasil)
          build: true
          nav:
            - Introdução: pt/index.md
            - Instalação: pt/install.md
            - Ajuste Fino: pt/finetune.md
            - Inferência: pt/inference.md
            - Amostras: pt/samples.md
        - locale: ko
          name: 한국어
          build: true
          nav:
            - 소개: ko/index.md
            - 설치: ko/install.md
            - 파인튜닝: ko/finetune.md
            - 추론: ko/inference.md
            - 샘플: ko/samples.md
        - locale: ar
          name: العربية
          build: true
          nav:
            - مقدمة: ar/index.md
            - التثبيت: ar/install.md
            - الضبط الدقيق: ar/finetune.md
            - الاستنتاج: ar/inference.md
            - العينات: ar/samples.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Es5qTB9BcN
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/fishaudio/fish-speech
    - icon: fontawesome/brands/qq
      link: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=jCKlUP7QgSm9kh95UlBoYv6s1I-Apl1M&authKey=xI5ttVAp3do68IpEYEalwXSYZFdfxZSkah%2BctF5FIMyN2NqAa003vFtLqJyAVRfF&noverify=0&group_code=593946093
  homepage: https://speech.fish.audio
