site_name: Fish Speech
site_description: Targeting SOTA TTS solutions.
site_url: https://speech.fish.audio

# Repository
repo_name: fishaudio/fish-speech
repo_url: https://github.com/fishaudio/fish-speech
edit_uri: blob/main/docs

# Copyright
copyright: Copyright &copy; 2023-2024 by Fish Audio

theme:
  name: material
  language: zh
  # logo: assets/images/icon_small.png
  favicon: assets/images/icon_small.png
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - navigation.prune
    - search
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - header.autohide
    

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      font:
        code: Roboto Mono

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      font:
        code: Roboto Mono
  
extra:
  homepage: https://speech.fish.audio

nav:
  - 首页: 
    - 首页: zh/index.md
    - 概述: zh/overview.md
    - 感谢名单: zh/thankslist.md
  - 安装:
    - 安装: zh/installation/overview.md
    - 背景知识: 
      - 观前提示: zh/installation/background/overview.md
      - git: zh/installation/background/git.md
      - conda环境: zh/installation/background/conda.md
      - 模型站的使用: zh/installation/background/hf.md
    - 在不同位置安装fish-speech:
      - linux: zh/installation/linux.md
      - docker: zh/installation/docker.md
      - WSL: zh/installation/wsl.md
      - windows: zh/installation/windows.md
      - 使用云服务器: zh/installation/cloud.md
  - 快速开始: 
    - 快速开始: zh/quick-start/overview.md
    - 终端: zh/quick-start/terminal.md
    - API接口: zh/quick-start/api.md
    - Webui: zh/quick-start/webui.md
  - 架构:
    - 概述: zh/frameworks/overview.md
    - VALL-E(X): zh/frameworks/vall-e.md
    - VQ-GAN: zh/frameworks/vq-gan.md
    - Llama: zh/frameworks/llama.md
  - 微调:
    - 微调: zh/finetuning/overview.md
    - VQ-GAN: zh/finetuning/vq-gan.md
    - Llama: zh/finetuning/llama.md
  - 示例: zh/samples.md
  - 更多功能:
    - whisper语音转文字: zh/utils/whisper.md
    - UVR人声提取: zh/utils/uvr.md

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - zh
        - en
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          nav:
            - Home: 
              - Home: en/index.md
              - Overview: en/overview.md
              - Thankslist: en/thankslist.md
            - Intallation:
              - Intallation: en/installation/overview.md
              - Background knowledges: 
                - Precautions: en/iinstallation/background/overview.md
                - Git: en/installation/background/git.md
                - Conda environment: en/installation/background/conda.md
                - Hugging Face: en/installation/background/hf.md
              - Install fish-speech in different places:
                - linux: en/installation/linux.md
                - docker: en/installation/docker.md
                - WSL: en/installation/wsl.md
                - windows: en/installation/windows.md
                - Use cloud server: en/installation/cloud.md
            - Quick Start: 
              - Quick Start: en/quick-start
              - Terminal: en/quick-start/terminal.md
              - API: en/quick-start/api.md
              - Webui: en/quick-start/webui.md
            - Frameworks:
              - Overview: en/frameworks/overview.md
              - VALL-E(X): en/frameworks/vall-e.md
              - VQ-GAN: en/frameworks/vq-gan.md
              - Llama: en/frameworks/llama.md
            - Fine-Tuning:
              - VQ-GAN: en/fine-tuning/vq-gan.md
              - Llama: en/fine-tuning/llama.md
            - Sample: en/samples.md
            - More Features:
              - whisper: en/utils/whisper.md
              - UVR: en/utils/uvr.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Es5qTB9BcN

extra_language:
  zh:
    site_name: Fish Speech
    site_url: https://speech.fish.audio/zh/
    